name: Build

on:
  pull_request:
    branches: [ xbox ]
  push:
    branches: [ xbox ]

jobs:        
  #BUILD XBOX
  Xbox:
    env:
      FILENAME_XBOX: 0

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install and Setup Dependencies
      run: |
        sudo apt-get update -y && sudo apt-get install -y flex bison clang lld llvm unzip
        git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/XboxDev/nxdk.git

    - name: Get Keen data
      run: |
        wget https://davidgow.net/keen/4keen14.zip
        unzip 4keen14.zip -d 4keen14
        mkdir bin
        mkdir bin/keen_data
        cp -a 4keen14/. bin/keen_data

    - name: Compile
      run: |
        eval $($(pwd)/nxdk/bin/activate -s)
        make -f Makefile.nxdk -j$(nproc)

    # Only create artifact on a push
    - if: github.event_name == 'push' 
      name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Omnispeak_ogxbox
        path: |
          bin/omnispeak_data
          bin/default.xbe
          bin/LICENSE.txt
          bin/xbox
          bin/keen_data
          CommanderKeen.iso
