name: Build

on:
  pull_request:
    branches: [ xbox-rebase ]
  push:
    branches: [ xbox-rebase ]

jobs:        
  #BUILD XBOX
  Xbox:
    env:
      FILENAME_XBOX: 0

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install and Setup Dependencies
      run: |
        sudo apt-get update -y && sudo apt-get install -y flex bison clang lld unzip
        git clone https://github.com/XboxDev/nxdk.git --recursive

        #Create output filename
        export FILENAME_XBOX=Omnispeak_Xbox_$(date -u +'%Y%m%d%H%M')
        echo "::set-env name=FILENAME_XBOX::$FILENAME_XBOX"

    - name: Get Keen data
      run: |
        wget https://davidgow.net/keen/4keen14.zip
        unzip 4keen14.zip -d 4keen14
        mkdir bin
        mkdir bin/keen_data
        cp -a 4keen14/. bin/keen_data

    - name: Compile
      run: |
        export PATH=$PATH:/usr/lib/llvm-6.0/bin
        make -f Makefile.nxdk -j$(nproc) NXDK_DIR=$(pwd)/nxdk

    # Only create artifact on a push
    - if: github.event_name == 'push' 
      name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.FILENAME_XBOX }}
        path: |
          bin/omnispeak_data
          bin/default.xbe
          bin/LICENSE.txt
          bin/xbox
          bin/keen_data
          CommanderKeen.iso
